### PR TITLE
Just new style update

### PR DESCRIPTION
**Pull request by ghost**
If needed can also remake content

### CODE REVIEW

**Comment by vnepogodin** [comment]
That won't work. That file is MDX so it has .mdx ext

**Comment by ghost** [comment]
> That won't work. That file is MDX so it has .mdx ext

I changed it from mdx to .md

**Comment by ptr1337** [comment]
> > That won't work. That file is MDX so it has .mdx ext
> 
> I changed it from mdx to .md

Actually, I think then importing pictures wont work. MDX is required for that.

**Comment by ghost** [comment]
> > > That won't work. That file is MDX so it has .mdx ext
> > 
> > 
> > I changed it from mdx to .md
> 
> Actually, I think then importing pictures wont work. MDX is required for that.

Should i just remove them or what to do with that?

**Comment by vnepogodin** [comment]
> > That won't work. That file is MDX so it has .mdx ext
> 
> I changed it from mdx to .md

yes. we need .mdx there

**Pull request closed without merging**
